# Generated by Django 4.2 on 2023-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
