# Generated by Django 4.2 on 2023-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_remove_books_bookfor_remove_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.DateField(),
        ),
    ]
