# Generated by Django 4.2 on 2023-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_books_bname'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Usergrand',
            field=models.CharField(choices=[('Grand', 'Grand'), ('Not Grant', 'Not Grant')], default='Grant', max_length=20),
        ),
    ]
