# Generated by Django 4.2 on 2023-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_register_usergrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Usergrand',
            field=models.CharField(choices=[('Grand', 'Grand'), ('Not Grant', 'Not Grant')], default='.....', max_length=20),
        ),
    ]
