# Generated by Django 4.2 on 2023-05-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_register_usergrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Usergrand',
            field=models.CharField(choices=[('Grand', 'Grand'), ('NotGrant', 'NotGrant')], default='NotGrant', max_length=20),
        ),
    ]
