# Generated by Django 4.2 on 2023-05-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_remove_books_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='about',
            field=models.CharField(default='', max_length=50),
        ),
    ]
