# Generated by Django 4.2 on 2023-05-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_books_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
