# Generated by Django 4.2 on 2023-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
