# Generated by Django 4.2 on 2023-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_register_address_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
