# Generated by Django 4.2 on 2023-05-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_alter_register_address_alter_register_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
