# Generated by Django 4.2 on 2023-05-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='bname',
            new_name='Books',
        ),
    ]
