# Generated by Django 4.2 on 2023-05-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_rename_bname_cart_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
