# Generated by Django 4.2 on 2023-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0024_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='purchased_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
