# Generated by Django 4.2 on 2023-05-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0025_books_purchased_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Books',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
