# Generated by Django 4.2 on 2023-05-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_remove_cartitem_books_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.register')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.register')),
            ],
        ),
    ]
