# Generated by Django 4.2 on 2023-05-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0027_order_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
