# Generated by Django 4.2 on 2023-05-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0028_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='bname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='public.books'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='public.register'),
        ),
    ]
