# Generated by Django 4.2 on 2023-05-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_alter_buyer_bname_alter_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Usergrand',
            new_name='user_grand',
        ),
    ]
