# Generated by Django 4.2 on 2023-05-28 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0030_rename_usergrand_register_user_grand'),
    ]

    operations = [
        migrations.AddField(
    model_name='buyer',
    name='quantity',
    field=models.IntegerField(default=0),
),
    ]
