# Generated by Django 4.2 on 2023-05-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0033_buyer_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
