# Generated by Django 4.2 on 2023-05-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0034_alter_register_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.register')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
