# Generated by Django 4.2 on 2023-05-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0035_check_out_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check_out',
            new_name='Order',
        ),
    ]
